#!/bin/sh
#
	echo ""
	echo "Assembling DSP code for a 3.5k x 3.5k x 4-readout LBNL CCD"
	echo ""
#
# DOWNLOAD selects application code to be loaded from EEPROM or 
#   downloaded from the host over the fiber optic link
#
# DOWNLOAD = HOST or ROM

DOWNLOAD=HOST
WAVEFORM_FILE=LBNL_3.5k.waveforms
DST_FILE=tim

asm56300 -b -ltim.ls -d DOWNLOAD $DOWNLOAD -d WAVEFORM_FILE "$WAVEFORM_FILE" tim.asm
dsplnk -btim.cld -v tim.cln 
rm -f "$DST_FILE".lod
cldlod tim.cld > "$DST_FILE".lod
rm tim.cln ; rm tim.cld

if [ "$DOWNLOAD" = "HOST" ] ; then
	echo ""
	echo "Created file 'tim.lod' for downloading over optical fiber"
	echo ""
fi

if [ "$DOWNLOAD" = "ROM" ] ; then
	echo ""
	echo "Created Motorola S-record file 'tim.s' for EEPROM burning"
	echo ""
	srec -bs tim.lod
	rm tim.lod 
fi
